import { qualsList } from "../whiteboard-config";

export const INITIAL_STATE = {
	aircrewById: {
		1: {
			id: 1,
			rank: 3,
			first: "Drew",
			last: "Willey",
			callsign: "Steamboat",
			seat: "wso",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
		2: {
			id: 2,
			rank: 3,
			first: "Alex",
			last: "Blank",
			callsign: "Jambo",
			seat: "pilot",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
		3: {
			id: 3,
			rank: 3,
			first: "Mark",
			last: "Infante",
			callsign: "Dump",
			seat: "pilot",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
	},
	allAircrew: [1,2,3],
	daysById: {},
	allDays: [],
	flightsById: {},
	allFlights: [],
	notesById: {},
	allNotes: [],
	crewList: {},
	sortiesById: {},
	allSorties: [],
	airspaceById: {},
	allAirspace: [],
	aircrewFormValues: {
		id: "",
		callsign: "",
		first: "",
		last: "",
		rank: 0,
		seat: "pilot",
		quals: [],
    	qualsList,
	},
};