import { qualsList } from "../whiteboard-config";

export const INITIAL_STATE = {
	aircrewById: {
		1: {
			id: 1,
			rank: 3,
			first: "Drew",
			last: "Willey",
			callsign: "Steamboat",
			seat: "wso",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
		2: {
			id: 2,
			rank: 3,
			first: "Alex",
			last: "Blank",
			callsign: "Jambo",
			seat: "pilot",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
		3: {
			id: 3,
			rank: 3,
			first: "Mark",
			last: "Infante",
			callsign: "Dump",
			seat: "pilot",
			quals: ['FAI'],
			flightPucks: [],
			simPucks: [],
			snivs: [],
			odos: 0,
			notes: [],
		},
	},
	allAircrew: [1,2,3],
	daysById: {
		'2018-01-24': {
			id: '2018-01-24',
			crewPucked: [],
			// flow: {
			// 	numJets: [],
			// 	method: [],
			// },
			// sun: {
			// 	rise: 0710,
			// 	set: 2031,
			// },
			flights: [1,2],
			notes: [],
		},
	},
	allDays: ['2018-01-24'],
	flightsById: {
		1: {
			id: 1,
			sim: false,
			// flow: "pit",
			times: {
				brief: "",
				takeoff: "",
				land: "",
			},
			airspace: [],
			sorties: [1,2],
			notes: [],
		},
		2: {
			id: 2,
			sim: false,
			// flow: "pit",
			times: {
				brief: "",
				takeoff: "",
				land: "",
			},
			airspace: [],
			sorties: [3,4],
			notes: [],
		},
	},
	allFlights: [1,2],
	notesById: {},
	allNotes: [],
	crewList: {
		currentDay: "2018-01-24",
	},
	sortiesById: {
		1: {
			id: 1,
			front: {
				inputName: "",
				crewId: 1,
				codes: [],
				symbols: [],
			},
			back: {
				inputName: "",
				crewId: 2,
				codes: [],
				symbols: [],
			},
			loadout: "",
			notes: [],
		},
		2: {
			id: 2,
			front: {
				inputName: "",
				crewId: 1,
				codes: [],
				symbols: [],
			},
			back: {
				inputName: "",
				crewId: 2,
				codes: [],
				symbols: [],
			},
			loadout: "",
			notes: [],
		},
		3: {
			id: 3,
			front: {
				inputName: "",
				crewId: 3,
				codes: [],
				symbols: [],
			},
			back: {
				inputName: "",
				crewId: 1,
				codes: [],
				symbols: [],
			},
			loadout: "",
			notes: [],
		},
		4: {
			id: 4,
			front: {
				inputName: "",
				crewId: 3,
				codes: [],
				symbols: [],
			},
			back: {
				inputName: "",
				crewId: 1,
				codes: [],
				symbols: [],
			},
			loadout: "",
			notes: [],
		},
	},
	allSorties: [1,2,3,4],
	airspaceById: {},
	allAirspace: [],
	addUpdateAircrewFormValues: {
		id: "",
		callsign: "",
		first: "",
		last: "",
		rank: 0,
		seat: "pilot",
		quals: [],
		existingAircrewUnchanged: false,
    	qualsList,
    	display: false,
	},
};